# Generated by Django 3.2.9 on 2021-12-10 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_Name', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('ZIPCode', models.IntegerField()),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_Name', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Parts', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemizedBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finish_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estimated_Price', models.IntegerField()),
                ('Deposit', models.FloatField()),
                ('Start_date', models.DateTimeField()),
                ('Estimated_Date', models.DateTimeField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesChops.customer')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesChops.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make', models.CharField(max_length=200)),
                ('Model', models.CharField(max_length=200)),
                ('Year', models.CharField(max_length=200)),
                ('Engine', models.CharField(max_length=200)),
                ('Trim', models.CharField(max_length=200)),
                ('Interior', models.CharField(max_length=200)),
                ('Exterior', models.CharField(max_length=200)),
                ('Body_Condition', models.CharField(max_length=200)),
                ('Frame_Condition', models.CharField(max_length=200)),
                ('Engine_Condition', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPhotoService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesChops.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Question', models.CharField(max_length=200)),
                ('Answer', models.CharField(blank=True, max_length=200, null=True)),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesChops.employee')),
                ('Service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesChops.questionphotoservice')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='Vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesChops.vehicle'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Photo_day', models.DateTimeField()),
                ('Service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesChops.questionphotoservice')),
            ],
        ),
        migrations.CreateModel(
            name='LaberCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stage', models.CharField(max_length=200)),
                ('Time', models.IntegerField()),
                ('Cost', models.FloatField()),
                ('Task', models.CharField(max_length=200)),
                ('Billing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesChops.itemizedbilling')),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesChops.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days', models.CharField(max_length=20)),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesChops.item')),
                ('Plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesChops.plan')),
            ],
        ),
        migrations.AddField(
            model_name='itemizedbilling',
            name='Plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesChops.plan'),
        ),
        migrations.CreateModel(
            name='ItemCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Stage', models.CharField(max_length=200)),
                ('Billing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesChops.itemizedbilling')),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesChops.item')),
            ],
        ),
    ]
